
###########################################################################
# PPQ/MQ IC50 paper FIGURE 1
#
# Makes three sets of figures:
# 1) PCA generated by Christian (code copied below) -- FIGURE 1A and 1B
# 2) PCA by geography -- FIGURE S1
# 3) Boxplots generated by me (code copied below) -- FIGURE 1C and 1D
# 
# Makes appearance consistent.  Exported files from #1 and #2 into Illustrator
# to put together.
#
###########################################################################




###################################################
################# Load Libraries ##################
###################################################

library(adegenet)
library(stringr)
library(pegas)
library(ggplot2)
library(gridExtra)
library(grid)


#####################################################
################# DEFINE FUNCTIONS ##################
#####################################################

## Function to create genlight from VCF.
genlight.maker <- function(infile) {
  loci <- read.vcf(infile)
  genlight <- new("genlight", loci) # convert data frame into genlight object
  ploidy(genlight) <- as.integer(1) # add back population information
  return(genlight)
}


#####################################################
############# DEFINE CONSISTENT THEMES ##############
#####################################################

## define theme
theme <- theme_bw() + 
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 18),
        legend.position = "none",
        plot.title = element_text(size = rel(2)))

#####################################################
#################### INPUT DATA #####################
#####################################################

## Read in VCF (JP: updated file 9/18/15 corrects SN084->SN094 label switch)
gl <- genlight.maker("../variants/slimmed.recode.84fix.vcf") # make genlight
indNames(gl) <- str_extract(indNames(gl), "[A-Z]+...") # fix the names

## Read in metadata
data <- read.table("data/PPQ_res_Mar18_2016.txt", sep="\t", header=TRUE)


#####################################################
################## CALCULATE PCA ####################
#####################################################

## Calculate PCA
pca <- glPca(gl, nf = 4)


#####################################################
########### K-MEANS CLUSTER ID & EXTRA PCs ##########
#####################################################

#####
## Identify clusters using K-means
#####
grp <- find.clusters(gl, n.pca = 3, max.n.clust = 10, choose.n.clust = FALSE, criterion = "diffNgroup")
dapc <- dapc(gl, grp$grp, n.pca = 3, n.da = 20)
  # using n.pca = 3 because these three PCs describe most of the variance

#####
## Plot the BIC for number of clusters
####
svg("num_clust.svg", width = 5, height = 4)
plot(grp$Kstat, type = "l", xlab = "Number of Clusters", ylab = "BIC", las = 1, xaxt = "n")
axis(1, at = 1:10)
points(grp$Kstat, pch = 19)
points(4, grp$Kstat[4], pch = 19, col = "red", cex = 1.2)
dev.off()

#####
## Create a DF with constant Jitter
#####
df <- as.data.frame(jitter(pca$scores, factor=900))

#####
## Define a useful plotting function
#####
kplot.pca <- function(df, plotname, pops, PCx, PCy) {
pic <- ggplot(df, aes_string(x=colnames(df)[PCx], y=colnames(df)[PCy])) + 
  geom_point(aes(size = 4, color = factor(dapc$grp)), alpha=0.8) +
  theme +
  scale_color_manual(values=palette) +
  labs(x = paste("PC", PCx, " - ", round(pca$eig[PCx]/sum(pca$eig)*100), "% variance", sep = ""),
       y = paste("PC", PCy, " - ", round(pca$eig[PCy]/sum(pca$eig)*100), "% variance", sep = "")) +
  theme(plot.margin=unit(c(1.5,1.5,1.5,1.5), "lines"))
return(pic)
}

#####
## Define the palette order
#####
palette <- c("deepskyblue", "brown1", "darkolivegreen3", "darkgoldenrod1")

#####
## Plot PCAs and the eigenvalues
#####
pf_1_2 <- kplot.pca(df, "", dapc$grp, 1, 2)
pf_1_3 <- kplot.pca(df, "", dapc$grp, 1, 3)
pf_2_3 <- kplot.pca(df, "", dapc$grp, 2, 3)
eigens <- ggplot(as.data.frame(pca$eig), aes(x=1:length(pca$eig), y = pca$eig/sum(pca$eig)*100)) + 
  geom_bar(stat = "identity") + 
  theme + 
  scale_y_continuous(limits=c(0, 30)) +
  labs(x = "PC eigenvalues", y = "% variance") +
  theme(plot.margin=unit(c(1.5,1.5,1.5,1.5), "lines"))

#####
## Arrange and print
#####
svg("extra_pcs.svg", width = 9, height = 8)
grid.arrange(eigens, pf_1_2, pf_1_3, pf_2_3, ncol = 2, padding = unit(10.0, "line"))
grid.text("A", x = unit(0.04, "npc"), y = unit(0.98, "npc"), gp=gpar(fontsize=27))
grid.text("B", x = unit(0.54, "npc"), y = unit(0.98, "npc"), gp=gpar(fontsize=27))
grid.text("C", x = unit(0.04, "npc"), y = unit(0.48, "npc"), gp=gpar(fontsize=27))
grid.text("D", x = unit(0.54, "npc"), y = unit(0.48, "npc"), gp=gpar(fontsize=27))
dev.off()



#####################################################
############### FIGURE 1 - PLOTTING #################
#####################################################

#####
## Prepare data: define based on PPQ and MQ IC50s
#####
id <- as.character(data$WGS_ID[data$WGS_ID %in% indNames(gl)])
ppq <- data$ppq_ic50[data$WGS_ID %in% indNames(gl)]
mq <- data$mq_ic50[data$WGS_ID %in% indNames(gl)]
ord <- match(indNames(gl), id) # got to match the order of JonP's metadata to the VCF
pop(gl) <-
  as.numeric(ppq[ord] > quantile(ppq[ord], na.rm=TRUE)[4]) + 
  as.numeric(mq[ord] > quantile(mq[ord], na.rm=TRUE)[4])*2



#####################################################
############### ggplot TO MAKE PCAs #################
#####################################################

#####
## Prepare data: define based on PPQ and MQ IC50s
#####

ppq200 <- ppq
ppq200[ppq200 > 200] <- 200
  # tamp down huge values to 200

#####
## Define the palette order
#####
palette <- c("deepskyblue", "brown1", "darkolivegreen3", "darkgoldenrod1")

#####
## Make the ggplots
#####

mq_pca <- ggplot(df, aes(x=PC1, y=PC2)) + 
  geom_point(aes(size = mq[ord], color = factor(dapc$grp)), alpha=0.7) +
  theme +
  scale_size_continuous(range = c(3,10)) +
  scale_color_manual(values=palette) +
  labs(title="Mefloquine\n",
       x = paste("PC", 1, " - ", round(pca$eig[1]/sum(pca$eig)*100), "% of the Variance", sep = ""),
       y = "  ") +
  scale_y_continuous(limits=c(-20, 20)) +
  scale_x_continuous(limits=c(-13, 30)) +
  theme(plot.margin=unit(c(1, 1, 0.5, 0.7), "lines"))

ppq_pca <- ggplot(df, aes(x=PC1, y=PC2)) + 
  geom_point(aes(size = ppq200[ord], color = factor(dapc$grp)), alpha=0.7) + 
  theme +
  scale_size_continuous(range = c(3,10)) +
  scale_color_manual(values=palette) +
  labs(title="Piperaquine\n",
       x = paste("PC", 1, " - ", round(pca$eig[1]/sum(pca$eig)*100), "% of the Variance", sep = ""),
       y = paste("PC", 2, " - ", round(pca$eig[2]/sum(pca$eig)*100), "% of the Variance", sep = "")) +
  scale_y_continuous(limits=c(-20, 20)) +
  scale_x_continuous(limits=c(-13, 30)) +
  theme(plot.margin=unit(c(1, 1, 0.5, 1), "lines"))
  

#####################################################
############### IMPORT BOXPLOT DATA #################
#####################################################

#imports data from JP's temp SAS work file, which I exported as text file.
jp_boxplot <- read.table("data/PPQ_res_Mar18_2016.txt", header=TRUE, sep = "\t")

#keeps only the samples assigned to a CP group (78 that underwent WGS, minus the three outliers)
jp_boxplot1 <- jp_boxplot[which(jp_boxplot$pca_group>0),]

#creates CP names for pca_group
jp_boxplot1$cp_name[jp_boxplot1$pca_group == 1] <- "CP1"
jp_boxplot1$cp_name[jp_boxplot1$pca_group == 2] <- "CP2"
jp_boxplot1$cp_name[jp_boxplot1$pca_group == 3] <- "CP3"
jp_boxplot1$cp_name[jp_boxplot1$pca_group == 4] <- "CP4"

# make PPQ boxplot
ppq_box <- ggplot(jp_boxplot1, aes(cp_name, ppq_ic50)) +
  geom_boxplot(aes(fill = cp_name)) +
  theme +
  theme(axis.title.x = element_blank()) +
  labs(y=expression(IC[50])) +
  scale_fill_manual(values = palette) +
  scale_y_continuous(limits=c(0, 200))

# make MQ boxplot
mq_box <- ggplot(jp_boxplot1, aes(cp_name, mq_ic50)) +
  geom_boxplot(aes(fill = cp_name)) +
  theme + 
  theme(axis.title.x = element_blank()) +
  labs(y="") +
  scale_fill_manual(values = palette) +
  scale_y_continuous(limits=c(0, 200))


########################################################################
# COMBINED FIGURE
########################################################################

svg("Figure 1 - PCAs and Boxplots.svg", width = 11, height = 10.5)

grid.arrange(ppq_pca, mq_pca, ppq_box, mq_box, ncol=2, heights=c(1.17, 1))
grid.text("A", x = unit(0.02, "npc"), y = unit(0.93, "npc"), gp=gpar(fontsize=30))
grid.text("B", x = unit(0.53, "npc"), y = unit(0.93, "npc"), gp=gpar(fontsize=30))
grid.text("C", x = unit(0.02, "npc"), y = unit(0.46, "npc"), gp=gpar(fontsize=30))
grid.text("D", x = unit(0.53, "npc"), y = unit(0.46, "npc"), gp=gpar(fontsize=30))
grid.text("*", x = unit(0.4251, "npc"), y = unit(0.41, "npc"), gp=gpar(fontsize=30))

dev.off()
